# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('identity', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=10000000000000000000)),
                ('category', models.CharField(choices=[('Transfer News', 'Transfer News'), ('Press Release', 'Press Release'), ('Basket Ball', 'Basket Ball'), ('Table Tennis', 'Table Tennis'), ('Scrabble', 'Scrabble'), ('Chess', 'Chess'), ('Handball', 'Handball'), ('Soccer', 'Soccer'), ('Volley Ball', 'Volley Ball'), ('Chess', 'Chess'), ('Atlethics', 'Athletics')], max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
